spring.application.name=vulnbank

# Base de datos H2 en memoria (se recrea en cada arranque)
spring.datasource.url=jdbc:h2:mem:vulnbank;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ejecuta schema.sql y data.sql al arrancar
spring.sql.init.mode=always

# Consola web de H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true
